services:
  cloudify-gitops-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudify-gitops-desiredstate-runner:latest
    env_file:
      - .env
    volumes:
      - .:/workspace
    working_dir: /workspace
