services:
  jenkins-cloudify:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    image: cloudify-jenkins-envops:latest
    container_name: cloudify-jenkins-envops
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    env_file:
      - .env.jenkins
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: ""
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./:/opt/cloudify-envops
    networks:
      - cloudify-jenkins-net

volumes:
  jenkins_home:

networks:
  cloudify-jenkins-net:
    name: cloudify-jenkins-net
