apiVersion: cloudify.windriver.com/v1
kind: CloudifyOperation

metadata:
  name: hello-dev-install

spec:
  deployment_ref: deployments/hello-dev.yaml
  workflow: install
  wait: true
  ensure_environment: true
  timeout_sec: 3600
  parameters: {}
