apiVersion: cloudify.windriver.com/v1
kind: CloudifyOperation
metadata:
  name: wr-demo-jenkins-wrcp-enrollment-configure
spec:
  deployment_id: wr-demo-jenkins-wrcp-enrollment
  workflow: execute_operation
  parameters:
    operation: cloudify.interfaces.lifecycle.configure
    node_ids:
      - wrcp_system
    run_by_dependency_order: true
    allow_kwargs_override: true
