apiVersion: cloudify.windriver.com/v1
kind: CloudifyOperation
metadata:
  name: wr-demo-jenkins-hello-install
spec:
  deployment_ref: deployments/wr-demo-jenkins-hello.yaml
  workflow: install
  wait: true
  ensure_environment: true
  timeout_sec: 3600
  parameters: {}








  
