#!/usr/bin/env python3
"""Production-oriented Cloudify lifecycle runner.

The script accepts one normalized request YAML generated by gitops_reconcile.py
or provided directly. It performs upload/create/execute/delete operations against
Cloudify Manager using REST API v3.1.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import shutil
import sys
import tempfile
import time
import uuid
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional

import requests
import yaml

TERMINAL_SUCCESS = {"terminated"}
TERMINAL_FAILURE = {"failed", "cancelled", "force_cancelling", "kill_cancelling", "canceled"}


def _strip(value: Optional[str]) -> str:
    return (value or "").strip()


def _bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def load_yaml(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ValueError(f"YAML must be an object: {path}")
    return data


def merge_yaml_files(files: list[Path]) -> Dict[str, Any]:
    merged: Dict[str, Any] = {}
    for file_path in files:
        data = load_yaml(file_path)
        merged.update(data)
    return merged


def mask(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 4:
        return "****"
    return value[:2] + "****" + value[-2:]


def setup_logging(log_dir: Path, level: str, run_id: str) -> logging.Logger:
    log_dir.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger("cloudify-lifecycle")
    logger.setLevel(getattr(logging, level.upper(), logging.INFO))
    logger.handlers.clear()
    formatter = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
    stream_handler = logging.StreamHandler(sys.stdout)
    stream_handler.setFormatter(formatter)
    file_handler = logging.FileHandler(log_dir / f"cloudify-lifecycle-{run_id}.log", encoding="utf-8")
    file_handler.setFormatter(formatter)
    logger.addHandler(stream_handler)
    logger.addHandler(file_handler)
    return logger


@dataclass
class LifecycleRequest:
    operation: str
    manager_url: str
    username: str
    password: str
    tenant: str
    api_version: str
    insecure: bool
    blueprint_id: str
    deployment_id: str
    blueprint_dir: Path
    application_file: str
    inputs_files: list[Path]
    inputs: Dict[str, Any]
    workflow: str
    workflow_parameters: Dict[str, Any]
    wait: bool
    request_timeout_sec: int
    execution_timeout_sec: int
    poll_interval_sec: int
    retry_count: int
    retry_backoff_sec: int
    delete_deployment: bool
    delete_blueprint: bool
    dry_run: bool
    ensure_environment: bool
    force_recreate_environment: bool
    recreate_uninstall_first: bool
    log_level: str
    log_dir: Path

    @staticmethod
    def from_dict(data: Dict[str, Any], base_dir: Path) -> "LifecycleRequest":
        operation = _strip(data.get("operation") or data.get("workflow") or "").lower()
        if operation not in {"create_environment", "execute_workflow", "delete_environment", "install", "update", "uninstall", "execute", "delete"}:
            raise ValueError("operation must be one of create_environment, execute_workflow, delete_environment, install, update, uninstall, execute, delete")

        manager_url = _strip(data.get("manager_url") or os.getenv("CFY_MANAGER_URL")).rstrip("/")
        username = _strip(data.get("username") or os.getenv("CFY_USERNAME"))
        password = _strip(data.get("password") or os.getenv("CFY_PASSWORD"))
        tenant = _strip(data.get("tenant") or os.getenv("CFY_TENANT") or "default_tenant")
        api_version = _strip(data.get("api_version") or os.getenv("CFY_API_VERSION") or "v3.1")
        insecure = _bool(data.get("insecure", os.getenv("CFY_INSECURE", "true")), True)
        blueprint_id = _strip(data.get("blueprint_id"))
        deployment_id = _strip(data.get("deployment_id"))
        blueprint_dir = (base_dir / _strip(data.get("blueprint_dir"))).resolve()
        application_file = _strip(data.get("application_file") or "blueprint.yaml")
        inputs_files = [(base_dir / _strip(p)).resolve() for p in data.get("inputs_files", [])]
        inputs = data.get("inputs") or {}
        workflow = _strip(data.get("workflow") or operation)
        workflow_parameters = data.get("workflow_parameters") or data.get("parameters") or {}
        if not isinstance(workflow_parameters, dict):
            raise ValueError("workflow_parameters/parameters must be a YAML object")
        log_dir = (base_dir / _strip(data.get("log_dir") or "logs")).resolve()

        req = LifecycleRequest(
            operation=operation,
            manager_url=manager_url,
            username=username,
            password=password,
            tenant=tenant,
            api_version=api_version,
            insecure=insecure,
            blueprint_id=blueprint_id,
            deployment_id=deployment_id,
            blueprint_dir=blueprint_dir,
            application_file=application_file,
            inputs_files=inputs_files,
            inputs=inputs,
            workflow=workflow,
            workflow_parameters=workflow_parameters,
            wait=_bool(data.get("wait"), True),
            request_timeout_sec=int(data.get("request_timeout_sec", 60)),
            execution_timeout_sec=int(data.get("execution_timeout_sec", 3600)),
            poll_interval_sec=int(data.get("poll_interval_sec", 10)),
            retry_count=int(data.get("retry_count", 5)),
            retry_backoff_sec=int(data.get("retry_backoff_sec", 5)),
            delete_deployment=_bool(data.get("delete_deployment"), operation in {"uninstall", "delete"}),
            delete_blueprint=_bool(data.get("delete_blueprint"), False),
            dry_run=_bool(data.get("dry_run"), False),
            ensure_environment=_bool(data.get("ensure_environment"), False),
            force_recreate_environment=_bool(data.get("force_recreate_environment"), False),
            recreate_uninstall_first=_bool(data.get("recreate_uninstall_first"), False),
            log_level=_strip(data.get("log_level") or "INFO"),
            log_dir=log_dir,
        )
        req.validate()
        return req

    def validate(self) -> None:
        missing = []
        for key in ["manager_url", "username", "password", "tenant", "api_version", "deployment_id"]:
            if not getattr(self, key):
                missing.append(key)
        if self.operation != "delete" and not self.blueprint_id:
            missing.append("blueprint_id")
        if missing:
            raise ValueError("Missing required values: " + ", ".join(missing))
        if self.operation in {"create_environment", "install", "update"}:
            if not self.blueprint_dir.is_dir():
                raise FileNotFoundError(f"blueprint_dir not found: {self.blueprint_dir}")
            if not (self.blueprint_dir / self.application_file).is_file():
                raise FileNotFoundError(f"application_file not found: {self.blueprint_dir / self.application_file}")
            for inputs_file in self.inputs_files:
                if not inputs_file.is_file():
                    raise FileNotFoundError(f"inputs file not found: {inputs_file}")


class CloudifyClient:
    def __init__(self, req: LifecycleRequest, logger: logging.Logger):
        self.req = req
        self.logger = logger
        self.base_url = f"{req.manager_url}/api/{req.api_version}"
        self.session = requests.Session()
        self.session.verify = not req.insecure
        self.session.headers.update({"Tenant": req.tenant})

    def _request(self, method: str, path: str, **kwargs: Any) -> requests.Response:
        url = f"{self.base_url}{path}"
        timeout = kwargs.pop("timeout", self.req.request_timeout_sec)

        # Production-safe default: every Cloudify API call must carry tenant and
        # authentication. The token call is retained as a credential validation
        # step, but subsequent calls also use Basic Auth because some Cloudify
        # deployments do not accept Bearer token format for all endpoints.
        headers = kwargs.pop("headers", {}) or {}
        headers.setdefault("Tenant", self.req.tenant)
        if "json" in kwargs:
            headers.setdefault("Content-Type", "application/json")
        kwargs.setdefault("auth", (self.req.username, self.req.password))

        last_error: Optional[Exception] = None
        for attempt in range(1, self.req.retry_count + 1):
            try:
                response = self.session.request(
                    method,
                    url,
                    headers=headers,
                    timeout=timeout,
                    **kwargs,
                )
                if response.status_code in {429, 500, 502, 503, 504} and attempt < self.req.retry_count:
                    self.logger.warning("Cloudify API returned %s for %s %s. Retrying attempt %s/%s", response.status_code, method, path, attempt, self.req.retry_count)
                    time.sleep(self.req.retry_backoff_sec * attempt)
                    continue
                return response
            except requests.RequestException as exc:
                last_error = exc
                if attempt < self.req.retry_count:
                    self.logger.warning("Cloudify API request failed for %s %s: %s. Retrying attempt %s/%s", method, path, exc, attempt, self.req.retry_count)
                    time.sleep(self.req.retry_backoff_sec * attempt)
                    continue
                raise
        raise RuntimeError(f"Cloudify request failed: {last_error}")

    def _ensure_ok(self, response: requests.Response, allowed: set[int]) -> requests.Response:
        if response.status_code not in allowed:
            body = response.text[:2000]
            raise RuntimeError(f"Cloudify API failure {response.status_code}: {body}")
        return response

    def authenticate(self) -> None:
        self.logger.info("Authenticating to Cloudify Manager: %s tenant=%s user=%s", self.req.manager_url, self.req.tenant, self.req.username)
        # Cloudify token API expects HTTP Basic authentication and JSON content type.
        # Some Cloudify versions reject an empty POST without application/json with:
        # 415 unsupported_content_type_error.
        response = self._request("POST", "/tokens", auth=(self.req.username, self.req.password), json={})
        self._ensure_ok(response, {200, 201})
        token = response.json().get("value") or response.json().get("token")
        if not token:
            raise RuntimeError("Cloudify token response did not contain a token value")
        # Do not set a Bearer token header here. Some Cloudify v3.1 deployments
        # require Basic Auth on follow-up endpoints such as blueprint upload.
        # _request() applies Basic Auth consistently to every API call.
        self.logger.info("Authenticated to Cloudify Manager")

    def blueprint_exists(self, blueprint_id: str) -> bool:
        response = self._request("GET", f"/blueprints/{blueprint_id}")
        if response.status_code == 404:
            return False
        self._ensure_ok(response, {200})
        return True

    def deployment_exists(self, deployment_id: str) -> bool:
        response = self._request("GET", f"/deployments/{deployment_id}")
        if response.status_code == 404:
            return False
        self._ensure_ok(response, {200})
        return True

    def create_blueprint_zip(self) -> Path:
        """Create a Cloudify-compatible blueprint archive.

        Cloudify Manager expects uploaded archives to contain exactly one top-level
        directory. The blueprint files must be placed under that directory, not
        directly at the zip root.
        """
        temp_dir = Path(tempfile.mkdtemp(prefix="cfy-bp-"))
        zip_path = temp_dir / f"{self.req.blueprint_id}.zip"
        top_dir = self.req.blueprint_dir.name
        entries = []
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
            for file_path in self.req.blueprint_dir.rglob("*"):
                if file_path.is_file():
                    arcname = Path(top_dir) / file_path.relative_to(self.req.blueprint_dir)
                    archive.write(file_path, arcname.as_posix())
                    entries.append(arcname.as_posix())
        if not entries:
            raise RuntimeError(f"Blueprint directory is empty: {self.req.blueprint_dir}")
        top_level = {entry.split('/')[0] for entry in entries}
        if len(top_level) != 1:
            raise RuntimeError(f"Invalid blueprint archive structure: expected one top-level directory, got {sorted(top_level)}")
        return zip_path

    def upload_blueprint(self) -> None:
        # Idempotent upload for GitOps/Jenkins repeated runs.
        # Cloudify returns 409 if the blueprint ID already exists. In this
        # environment+operation model, existing blueprint is safe to reuse;
        # major blueprint changes should use a new blueprint_id or a controlled
        # force recreate/update policy.
        if self.blueprint_exists(self.req.blueprint_id):
            self.logger.info("Blueprint '%s' already exists; skipping upload", self.req.blueprint_id)
            return
        zip_path = self.create_blueprint_zip()
        self.logger.info("Uploading blueprint '%s' from %s", self.req.blueprint_id, zip_path)
        try:
            with zip_path.open("rb") as handle:
                files = {"blueprint_archive": (zip_path.name, handle, "application/zip")}
                params = {"application_file_name": self.req.application_file}
                response = self._request("PUT", f"/blueprints/{self.req.blueprint_id}", params=params, files=files, timeout=max(self.req.request_timeout_sec, 120))
                if response.status_code == 409:
                    self.logger.info("Blueprint '%s' already exists; treating upload as idempotent success", self.req.blueprint_id)
                    return
                self._ensure_ok(response, {200, 201})
        finally:
            shutil.rmtree(zip_path.parent, ignore_errors=True)

    def create_deployment(self) -> None:
        inputs = merge_yaml_files(self.req.inputs_files)
        inputs.update(self.req.inputs)
        self.logger.info("Creating deployment '%s' from blueprint '%s'", self.req.deployment_id, self.req.blueprint_id)
        self.logger.info("Deployment inputs: %s", json.dumps(inputs, sort_keys=True))
        payload = {"blueprint_id": self.req.blueprint_id, "inputs": inputs}
        response = self._request("PUT", f"/deployments/{self.req.deployment_id}", json=payload)
        self._ensure_ok(response, {200, 201})

    def start_execution(self, workflow: str) -> str:
        self.logger.info("Starting workflow '%s' on deployment '%s'", workflow, self.req.deployment_id)
        if self.req.workflow_parameters:
            self.logger.info("Workflow parameters: %s", json.dumps(self.req.workflow_parameters, sort_keys=True))
        payload = {"deployment_id": self.req.deployment_id, "workflow_id": workflow, "parameters": self.req.workflow_parameters, "allow_custom_parameters": True}
        response = self._request("POST", "/executions", json=payload)
        self._ensure_ok(response, {200, 201})
        execution_id = response.json().get("id")
        if not execution_id:
            raise RuntimeError("Execution response did not contain execution id")
        return execution_id

    def wait_for_execution(self, execution_id: str) -> str:
        deadline = time.time() + self.req.execution_timeout_sec
        last_status = "unknown"
        while time.time() < deadline:
            response = self._request("GET", f"/executions/{execution_id}")
            self._ensure_ok(response, {200})
            data = response.json()
            status = str(data.get("status", "unknown")).lower()
            if status != last_status:
                self.logger.info("Execution %s status: %s", execution_id, status)
                last_status = status
            if status in TERMINAL_SUCCESS:
                return status
            if status in TERMINAL_FAILURE:
                raise RuntimeError(f"Execution {execution_id} ended with status: {status}")
            time.sleep(self.req.poll_interval_sec)
        raise TimeoutError(f"Execution {execution_id} timed out after {self.req.execution_timeout_sec}s")

    def delete_deployment(self) -> None:
        if not self.deployment_exists(self.req.deployment_id):
            self.logger.info("Deployment '%s' already absent", self.req.deployment_id)
            return
        self.logger.info("Deleting deployment '%s'", self.req.deployment_id)
        response = self._request("DELETE", f"/deployments/{self.req.deployment_id}")
        self._ensure_ok(response, {200, 204})

    def delete_blueprint(self) -> None:
        if not self.blueprint_exists(self.req.blueprint_id):
            self.logger.info("Blueprint '%s' already absent", self.req.blueprint_id)
            return
        self.logger.info("Deleting blueprint '%s'", self.req.blueprint_id)
        response = self._request("DELETE", f"/blueprints/{self.req.blueprint_id}")
        self._ensure_ok(response, {200, 204})


def execute(req: LifecycleRequest, logger: logging.Logger) -> Dict[str, Any]:
    summary: Dict[str, Any] = {
        "run_id": None,
        "operation": req.operation,
        "blueprint_id": req.blueprint_id,
        "deployment_id": req.deployment_id,
        "workflow": req.workflow,
        "status": "started",
    }
    logger.info("Lifecycle request: operation=%s blueprint_id=%s deployment_id=%s workflow=%s manager=%s user=%s password=%s",
                req.operation, req.blueprint_id, req.deployment_id, req.workflow, req.manager_url, req.username, mask(req.password))
    if req.dry_run:
        logger.info("Dry-run enabled. Validation passed; no Cloudify API calls will be made.")
        summary["status"] = "dry-run"
        return summary

    client = CloudifyClient(req, logger)
    client.authenticate()

    if req.operation == "create_environment":
        client.upload_blueprint()
        exists = client.deployment_exists(req.deployment_id)
        if exists and req.force_recreate_environment:
            logger.info("Cloudify deployment '%s' already exists and force_recreate_environment=true", req.deployment_id)
            if req.recreate_uninstall_first:
                try:
                    logger.info("Running uninstall workflow before recreate for deployment '%s'", req.deployment_id)
                    execution_id = client.start_execution("uninstall")
                    if req.wait:
                        client.wait_for_execution(execution_id)
                except Exception as exc:  # noqa: BLE001
                    logger.warning("Uninstall before recreate failed or was not required: %s", exc)
            client.delete_deployment()
            exists = False
        if not exists:
            client.create_deployment()
            logger.info("Cloudify environment/deployment '%s' created", req.deployment_id)
        else:
            logger.info("Cloudify environment/deployment '%s' already exists; create_environment is idempotent", req.deployment_id)

    elif req.operation in {"install", "update"}:
        # Backward-compatible mode: create/reuse environment and immediately execute the workflow.
        client.upload_blueprint()
        if not client.deployment_exists(req.deployment_id):
            client.create_deployment()
        else:
            logger.info("Deployment '%s' already exists; reusing it", req.deployment_id)
        execution_id = client.start_execution(req.workflow)
        summary["execution_id"] = execution_id
        if req.wait:
            summary["execution_status"] = client.wait_for_execution(execution_id)

    elif req.operation in {"execute", "execute_workflow"}:
        if not client.deployment_exists(req.deployment_id):
            if req.ensure_environment:
                logger.info("Deployment '%s' not found; ensure_environment=true, creating Cloudify environment before workflow execution", req.deployment_id)
                client.upload_blueprint()
                client.create_deployment()
            else:
                raise RuntimeError(f"Deployment not found: {req.deployment_id}. Commit the deployment desired-state file first to create the environment, or set ensure_environment: true on the operation intent.")
        execution_id = client.start_execution(req.workflow)
        summary["execution_id"] = execution_id
        if req.wait:
            summary["execution_status"] = client.wait_for_execution(execution_id)

    elif req.operation == "uninstall":
        if client.deployment_exists(req.deployment_id):
            execution_id = client.start_execution(req.workflow)
            summary["execution_id"] = execution_id
            if req.wait:
                summary["execution_status"] = client.wait_for_execution(execution_id)
        else:
            logger.info("Deployment '%s' already absent; skipping uninstall workflow", req.deployment_id)
        if req.delete_deployment:
            client.delete_deployment()
        if req.delete_blueprint:
            client.delete_blueprint()

    elif req.operation in {"delete", "delete_environment"}:
        if req.delete_deployment:
            client.delete_deployment()
        if req.delete_blueprint and req.blueprint_id:
            client.delete_blueprint()

    summary["status"] = "success"
    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description="Execute Cloudify lifecycle request")
    parser.add_argument("--request", required=True, help="Path to normalized lifecycle request YAML")
    args = parser.parse_args()

    base_dir = Path.cwd()
    run_id = uuid.uuid4().hex[:12]
    try:
        data = load_yaml(Path(args.request))
        log_dir = base_dir / _strip(data.get("log_dir") or "logs")
        log_level = _strip(data.get("log_level") or "INFO")
        logger = setup_logging(log_dir, log_level, run_id)
        req = LifecycleRequest.from_dict(data, base_dir)
        logger.info("Run ID: %s", run_id)
        summary = execute(req, logger)
        summary["run_id"] = run_id
        summary_path = req.log_dir / f"cloudify-lifecycle-{run_id}.summary.json"
        summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True), encoding="utf-8")
        logger.info("Lifecycle operation completed successfully. Summary: %s", summary_path)
        return 0
    except Exception as exc:  # noqa: BLE001 - CLI should report all failures cleanly
        fallback_log_dir = Path.cwd() / "logs"
        fallback_log_dir.mkdir(parents=True, exist_ok=True)
        logger = logging.getLogger("cloudify-lifecycle")
        if not logger.handlers:
            logger = setup_logging(fallback_log_dir, "INFO", run_id)
        logger.exception("Lifecycle operation failed: %s", exc)
        summary_path = fallback_log_dir / f"cloudify-lifecycle-{run_id}.summary.json"
        summary_path.write_text(json.dumps({"run_id": run_id, "status": "failed", "error": str(exc)}, indent=2), encoding="utf-8")
        return 1


if __name__ == "__main__":
    sys.exit(main())
